[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Швидкість Монітора порту
monitor_speed = 115200

; Автоматичне завантаження бібліотеки для MLX90614
lib_deps = 
	adafruit/Adafruit MLX90614 Library @ ^2.1.5